In [86]:
import pandas as pd

In [ ]:
df =(r"C:\Git_test\Digital Native Challenge\vgsales.csv") pd.read_csv

In [88]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [89]:
platform_rename_map = {
    "PS2":  "PlayStation 2",
    "X360": "Xbox 360",
    "PS3":  "PlayStation 3",
    "Wii":  "Wii",
    "DS":   "Nintendo DS",
    "PS":   "PlayStation 1",
    "GBA":  "Game Boy Advance",
    "PS4":  "PlayStation 4",
    "PCFX": "PC-FX Interactive",
    "GB":   "Game Boy",
    "XB":   "Xbox Original",
    "NES":  "Nintendo Entertainment System",
    "3DS":  "Nintendo 3DS",
    "N64":  "Nintendo 64",
    "SNES": "Super Nintendo Entertainment System",
    "GEN":  "Sega Genesis",
    "XOne": "Xbox One",
    "2600": "Atari 2600",
    "WiiU": "Wii U",
    "PSP":  "PlayStation Portable",
    "SAT":  "Sega Saturn",
    "DC":   "Dreamcast",
    "SCD":  "Sega CD Video",
    "NG":   "Neo Geo",
    "WS":   "Wonder Swan",
    "TG16": "Turbo Grafx 16",
    "3DO":  "3DO Interactive",
    "GG":   "Game Gear",
    "PC":   "Portable Computer",
    "GC":   "GameCube",
    "3DS":  "Nintendo 3DS",
    "PC": "Personal Computer",
    "PSV": "PlayStation Vita",

}


df["Platform"] = df["Platform"].map(platform_rename_map)


print(df['Platform'])

0                                  Wii
1        Nintendo Entertainment System
2                                  Wii
3                                  Wii
4                             Game Boy
                     ...
16593                 Game Boy Advance
16594                         GameCube
16595                    PlayStation 2
16596                      Nintendo DS
16597                 Game Boy Advance
Name: Platform, Length: 16598, dtype: object

In [90]:
df['Year'].head(10)

0    2006.0
1    1985.0
2    2008.0
3    2009.0
4    1996.0
5    1989.0
6    2006.0
7    2006.0
8    2009.0
9    1984.0
Name: Year, dtype: float64

In [91]:
min_year = df['Year'].min()
max_year = df['Year'].max()

print(f"Year range in data: {min_year} to {max_year}")

Year range in data: 1980.0 to 2020.0

In [92]:
sales_rename_map = {
    "EU_Sales": "Europe Sales",
    "JP_Sales": "Asia Sales",
    "Global_Sales": "Global Sales",
    "Other_Sales": "Africa Sales",
    "NA_Sales": "America Sales"
}

df = df.rename(columns=sales_rename_map)
print(df.columns)

Index(['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher',
       'America Sales', 'Europe Sales', 'Asia Sales', 'Africa Sales',
       'Global Sales'],
      dtype='object')

In [93]:
df.isna().sum()

Rank               0
Name               0
Platform           0
Year             271
Genre              0
Publisher         58
America Sales      0
Europe Sales       0
Asia Sales         0
Africa Sales       0
Global Sales       0
dtype: int64

In [94]:
NA_rows = df[df['Year'].isna()].index.tolist()

NA_rows

[179,
 377,
 431,
 470,
 607,
 624,
 649,
 652,
 711,
 782,
 1126,
 1133,
 1303,
 1433,
 1498,
 1513,
 1585,
 1649,
 1697,
 1837,
 1990,
 2019,
 2086,
 2113,
 2114,
 2134,
 2145,
 2173,
 2286,
 2295,
 2415,
 2422,
 2484,
 2497,
 2528,
 2586,
 2776,
 2786,
 2838,
 2947,
 3049,
 3141,
 3194,
 3217,
 3238,
 3346,
 3421,
 3468,
 3501,
 3715,
 3753,
 3880,
 3952,
 4145,
 4151,
 4199,
 4232,
 4330,
 4378,
 4380,
 4469,
 4472,
 4536,
 4683,
 4791,
 4797,
 4858,
 4865,
 4934,
 5061,
 5078,
 5162,
 5171,
 5195,
 5196,
 5240,
 5302,
 5508,
 5618,
 5625,
 5657,
 5669,
 5769,
 5798,
 5838,
 5861,
 5870,
 5901,
 5913,
 6042,
 6125,
 6153,
 6195,
 6211,
 6272,
 6283,
 6314,
 6316,
 6319,
 6401,
 6496,
 6647,
 6777,
 6806,
 6832,
 6919,
 6926,
 6937,
 6966,
 6968,
 7035,
 7181,
 7213,
 7351,
 7369,
 7370,
 7382,
 7406,
 7423,
 7615,
 7648,
 7720,
 7908,
 7946,
 8044,
 8086,
 8157,
 8167,
 8204,
 8223,
 8313,
 8334,
 8376,
 8439,
 8553,
 8620,
 8707,
 8760,
 8899,
 8929,
 9081,
 9151,
 9171,
 9251,
 9310,
 9392,
 9475,
 9522,
 9667,
 9692,
 9742,
 9749,
 9769,
 9815,
 9820,
 9821,
 9840,
 9868,
 9981,
 10045,
 10272,
 10362,
 10465,
 10494,
 10559,
 10690,
 10758,
 10792,
 10829,
 10979,
 10997,
 11076,
 11108,
 11142,
 11323,
 11331,
 11376,
 11409,
 11455,
 11543,
 11573,
 11755,
 11798,
 11921,
 11938,
 11976,
 12015,
 12028,
 12127,
 12129,
 12135,
 12184,
 12212,
 12238,
 12248,
 12487,
 12517,
 12531,
 12626,
 12666,
 12709,
 12749,
 12807,
 12825,
 12879,
 12915,
 12922,
 12929,
 13055,
 13156,
 13278,
 13477,
 13665,
 13672,
 13675,
 13733,
 13870,
 13962,
 14046,
 14055,
 14056,
 14087,
 14098,
 14160,
 14273,
 14296,
 14312,
 14377,
 14473,
 14522,
 14583,
 14676,
 14696,
 14849,
 14855,
 14876,
 14925,
 14942,
 14997,
 14998,
 14999,
 15197,
 15208,
 15261,
 15316,
 15476,
 15579,
 15606,
 15652,
 15697,
 15717,
 15739,
 15811,
 15865,
 15876,
 15878,
 15900,
 15915,
 16057,
 16058,
 16065,
 16191,
 16194,
 16198,
 16229,
 16246,
 16307,
 16327,
 16366,
 16427,
 16493]

In [95]:
df[df['Year'].isna()][['Global Sales']]

       Global Sales
179            5.23
377            3.49
431            3.17
470            3.00
607            2.53
...             ...
16307          0.01
16327          0.01
16366          0.01
16427          0.01
16493          0.01

[271 rows x 1 columns]

In [96]:
print(df['Year'])

0        2006.0
1        1985.0
2        2008.0
3        2009.0
4        1996.0
          ...
16593    2002.0
16594    2003.0
16595    2008.0
16596    2010.0
16597    2003.0
Name: Year, Length: 16598, dtype: float64

In [97]:
print (df['Year'].dtype)

float64

In [98]:
df['Year'] = pd.to_datetime(df['Year'], format='%Y')
print (df['Year'].dtype)

datetime64[ns]

In [99]:
print(df['Publisher'].isna().sum())

58

In [100]:
df['Publisher'] = df['Publisher'].fillna('Unknown')

In [101]:
print(df['Publisher'].isna().sum())

0

In [102]:
print (df['Global Sales'].dtype)

float64

In [103]:
df['Global Sales'] = df['Global Sales'].apply(lambda x: f"{x: .2f}")

In [104]:
df.to_csv(r"C:\Git_test\Digital Native Challenge\Vgsales_Cleaned_Data_test.csv", index=False)